-- Създаване на таблицата properties
CREATE TABLE IF NOT EXISTS properties (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title_bg VARCHAR(255) NOT NULL,
    title_de VARCHAR(255) NOT NULL,
    title_ru VARCHAR(255) NOT NULL,
    title_en VARCHAR(255) NOT NULL,
    price DECIMAL(10,2) NOT NULL,
    area DECIMAL(10,2) NOT NULL,
    type VARCHAR(50) NOT NULL,
    status ENUM('available', 'reserved', 'rented', 'sold') NOT NULL,
    location_bg VARCHAR(255) NOT NULL,
    location_de VARCHAR(255) NOT NULL,
    location_ru VARCHAR(255) NOT NULL,
    location_en VARCHAR(255) NOT NULL,
    address VARCHAR(255),
    featured TINYINT(1) DEFAULT 0,
    specification_bg TEXT,
    specification_de TEXT,
    specification_ru TEXT,
    specification_en TEXT,
    description_bg TEXT,
    description_de TEXT,
    description_ru TEXT,
    description_en TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX idx_property_type (type),
    INDEX idx_property_status (status),
    INDEX idx_property_featured (featured)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 