CREATE TABLE properties (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title_bg VARCHAR(255) NOT NULL,
    title_de VARCHAR(255) NOT NULL,
    title_ru VARCHAR(255) NOT NULL,
    description_bg TEXT,
    description_de TEXT,
    description_ru TEXT,
    type ENUM('industrial', 'office', 'retail', 'warehouse') NOT NULL,
    status ENUM('available', 'rented', 'sold') NOT NULL DEFAULT 'available',
    price DECIMAL(12,2) NOT NULL,
    area DECIMAL(10,2) NOT NULL,
    location_bg VARCHAR(255) NOT NULL,
    location_de VARCHAR(255) NOT NULL,
    location_ru VARCHAR(255) NOT NULL,
    address VARCHAR(255) NOT NULL,
    lat DECIMAL(10,8),
    lng DECIMAL(11,8),
    built_year INT,
    last_renovation INT,
    floors INT,
    parking_spots INT,
    ceiling_height DECIMAL(4,2),
    office_space DECIMAL(10,2),
    storage_space DECIMAL(10,2),
    production_space DECIMAL(10,2),
    heating BOOLEAN DEFAULT 0,
    electricity BOOLEAN DEFAULT 0,
    water_supply BOOLEAN DEFAULT 0,
    security BOOLEAN DEFAULT 0,
    loading_docks INT DEFAULT 0,
    virtual_tour_url VARCHAR(255),
    featured BOOLEAN DEFAULT 0,
    created_by INT,
    updated_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (updated_by) REFERENCES users(id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci; 